package com.example.mridul.RetailerJunction.daogenerator.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ANALYTICS_LOCATION".
 */
public class AnalyticsLocation {

    private Long id;
    private String locationidentifier;
    private Double latitude;
    private Double longitude;
    private Integer locationkey;
    private Long locationdate;
    private String locationname;
    private String locationextraidentifier;

    public AnalyticsLocation() {
    }

    public AnalyticsLocation(Long id) {
        this.id = id;
    }

    public AnalyticsLocation(Long id, String locationidentifier, Double latitude, Double longitude, Integer locationkey, Long locationdate, String locationname, String locationextraidentifier) {
        this.id = id;
        this.locationidentifier = locationidentifier;
        this.latitude = latitude;
        this.longitude = longitude;
        this.locationkey = locationkey;
        this.locationdate = locationdate;
        this.locationname = locationname;
        this.locationextraidentifier = locationextraidentifier;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLocationidentifier() {
        return locationidentifier;
    }

    public void setLocationidentifier(String locationidentifier) {
        this.locationidentifier = locationidentifier;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Integer getLocationkey() {
        return locationkey;
    }

    public void setLocationkey(Integer locationkey) {
        this.locationkey = locationkey;
    }

    public Long getLocationdate() {
        return locationdate;
    }

    public void setLocationdate(Long locationdate) {
        this.locationdate = locationdate;
    }

    public String getLocationname() {
        return locationname;
    }

    public void setLocationname(String locationname) {
        this.locationname = locationname;
    }

    public String getLocationextraidentifier() {
        return locationextraidentifier;
    }

    public void setLocationextraidentifier(String locationextraidentifier) {
        this.locationextraidentifier = locationextraidentifier;
    }

}
