package com.example.mridul.RetailerJunction.daogenerator.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CLOUD_APP_DETAILS".
 */
public class CloudAppDetails {

    private Long campaignId;
    private String name;
    private String version;
    private Integer size;
    private String downloadurl;
    private String packagename;
    private String checksum;
    private Integer state;
    private Long listts;
    private Boolean downloaded;
    private Long apkts;

    public CloudAppDetails() {
    }

    public CloudAppDetails(Long campaignId) {
        this.campaignId = campaignId;
    }

    public CloudAppDetails(Long campaignId, String name, String version, Integer size, String downloadurl, String packagename, String checksum, Integer state, Long listts, Boolean downloaded, Long apkts) {
        this.campaignId = campaignId;
        this.name = name;
        this.version = version;
        this.size = size;
        this.downloadurl = downloadurl;
        this.packagename = packagename;
        this.checksum = checksum;
        this.state = state;
        this.listts = listts;
        this.downloaded = downloaded;
        this.apkts = apkts;
    }

    public Long getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public String getDownloadurl() {
        return downloadurl;
    }

    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl;
    }

    public String getPackagename() {
        return packagename;
    }

    public void setPackagename(String packagename) {
        this.packagename = packagename;
    }

    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Long getListts() {
        return listts;
    }

    public void setListts(Long listts) {
        this.listts = listts;
    }

    public Boolean getDownloaded() {
        return downloaded;
    }

    public void setDownloaded(Boolean downloaded) {
        this.downloaded = downloaded;
    }

    public Long getApkts() {
        return apkts;
    }

    public void setApkts(Long apkts) {
        this.apkts = apkts;
    }

}
