package com.example.mridul.RetailerJunction.daogenerator.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CLOUD_APP_DETAILS".
 */
public class CloudAppDetails {

    private Long id;
    private Integer campaign_id;
    private String name;
    private String version;
    private Integer size;
    private String downloadurl;
    private String packagename;
    private String md5;
    private Integer state;
    private Long ts;

    public CloudAppDetails() {
    }

    public CloudAppDetails(Long id) {
        this.id = id;
    }

    public CloudAppDetails(Long id, Integer campaign_id, String name, String version, Integer size, String downloadurl, String packagename, String md5, Integer state, Long ts) {
        this.id = id;
        this.campaign_id = campaign_id;
        this.name = name;
        this.version = version;
        this.size = size;
        this.downloadurl = downloadurl;
        this.packagename = packagename;
        this.md5 = md5;
        this.state = state;
        this.ts = ts;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCampaign_id() {
        return campaign_id;
    }

    public void setCampaign_id(Integer campaign_id) {
        this.campaign_id = campaign_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public String getDownloadurl() {
        return downloadurl;
    }

    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl;
    }

    public String getPackagename() {
        return packagename;
    }

    public void setPackagename(String packagename) {
        this.packagename = packagename;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Long getTs() {
        return ts;
    }

    public void setTs(Long ts) {
        this.ts = ts;
    }

}
