package com.example.mridul.RetailerJunction.daogenerator.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.mridul.RetailerJunction.daogenerator.model.CloudAppDetails;
import com.example.mridul.RetailerJunction.daogenerator.model.InstallRecords;

import com.example.mridul.RetailerJunction.daogenerator.model.CloudAppDetailsDao;
import com.example.mridul.RetailerJunction.daogenerator.model.InstallRecordsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cloudAppDetailsDaoConfig;
    private final DaoConfig installRecordsDaoConfig;

    private final CloudAppDetailsDao cloudAppDetailsDao;
    private final InstallRecordsDao installRecordsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cloudAppDetailsDaoConfig = daoConfigMap.get(CloudAppDetailsDao.class).clone();
        cloudAppDetailsDaoConfig.initIdentityScope(type);

        installRecordsDaoConfig = daoConfigMap.get(InstallRecordsDao.class).clone();
        installRecordsDaoConfig.initIdentityScope(type);

        cloudAppDetailsDao = new CloudAppDetailsDao(cloudAppDetailsDaoConfig, this);
        installRecordsDao = new InstallRecordsDao(installRecordsDaoConfig, this);

        registerDao(CloudAppDetails.class, cloudAppDetailsDao);
        registerDao(InstallRecords.class, installRecordsDao);
    }
    
    public void clear() {
        cloudAppDetailsDaoConfig.getIdentityScope().clear();
        installRecordsDaoConfig.getIdentityScope().clear();
    }

    public CloudAppDetailsDao getCloudAppDetailsDao() {
        return cloudAppDetailsDao;
    }

    public InstallRecordsDao getInstallRecordsDao() {
        return installRecordsDao;
    }

}
