package com.example.mridul.RetailerJunction.daogenerator.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EVENT".
 */
public class Event {

    private Long id;
    private String name;
    private String value;
    private String extraname;
    private Boolean issent;
    private java.util.Date date;
    private Integer count;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, String name, String value, String extraname, Boolean issent, java.util.Date date, Integer count) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.extraname = extraname;
        this.issent = issent;
        this.date = date;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getExtraname() {
        return extraname;
    }

    public void setExtraname(String extraname) {
        this.extraname = extraname;
    }

    public Boolean getIssent() {
        return issent;
    }

    public void setIssent(Boolean issent) {
        this.issent = issent;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
