package com.example.mridul.RetailerJunction.daogenerator.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.mridul.RetailerJunction.daogenerator.model.InstallRecords;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INSTALL_RECORDS".
*/
public class InstallRecordsDao extends AbstractDao<InstallRecords, Long> {

    public static final String TABLENAME = "INSTALL_RECORDS";

    /**
     * Properties of entity InstallRecords.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Json_data = new Property(1, String.class, "json_data", false, "JSON_DATA");
        public final static Property Timestamp = new Property(2, long.class, "timestamp", false, "TIMESTAMP");
        public final static Property IsUploaded = new Property(3, int.class, "isUploaded", false, "IS_UPLOADED");
    };


    public InstallRecordsDao(DaoConfig config) {
        super(config);
    }
    
    public InstallRecordsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INSTALL_RECORDS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JSON_DATA\" TEXT NOT NULL ," + // 1: json_data
                "\"TIMESTAMP\" INTEGER NOT NULL ," + // 2: timestamp
                "\"IS_UPLOADED\" INTEGER NOT NULL );"); // 3: isUploaded
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INSTALL_RECORDS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, InstallRecords entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJson_data());
        stmt.bindLong(3, entity.getTimestamp());
        stmt.bindLong(4, entity.getIsUploaded());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public InstallRecords readEntity(Cursor cursor, int offset) {
        InstallRecords entity = new InstallRecords( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // json_data
            cursor.getLong(offset + 2), // timestamp
            cursor.getInt(offset + 3) // isUploaded
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, InstallRecords entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJson_data(cursor.getString(offset + 1));
        entity.setTimestamp(cursor.getLong(offset + 2));
        entity.setIsUploaded(cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(InstallRecords entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(InstallRecords entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
