package com.example.mridul.RetailerJunction.daogenerator.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INSTALL_RECORDS".
 */
public class InstallRecords {

    private Long id;
    /** Not-null value. */
    private String json_data;
    private long timestamp;
    private int isUploaded;

    public InstallRecords() {
    }

    public InstallRecords(Long id) {
        this.id = id;
    }

    public InstallRecords(Long id, String json_data, long timestamp, int isUploaded) {
        this.id = id;
        this.json_data = json_data;
        this.timestamp = timestamp;
        this.isUploaded = isUploaded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getJson_data() {
        return json_data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJson_data(String json_data) {
        this.json_data = json_data;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public int getIsUploaded() {
        return isUploaded;
    }

    public void setIsUploaded(int isUploaded) {
        this.isUploaded = isUploaded;
    }

}
